### ISSUE TITLE
How to test

### ISSUE THREAD

**Issue by building39** [perfectline/validates_url#67]
I have this test:
```require 'spec_helper'

describe "RSpec matcher" do
  subject { User }

  it "should ensure that attributes are validated" do
    should validate_url_of(:homepage)
  end
end'''

It fails with `undefined method`:

```Run options: include {:locations=>{"./spec/models/xxx.rb"=>[3]}}
F

Failures:

  1) RSpec matcher should ensure that attributes are validated
     Failure/Error: should validate_url_of(:homepage)
     
     NoMethodError:
       undefined method `validate_url_of' for #<RSpec::ExampleGroups::RSpecMatcher:0x0000000138ed88>
     # ./spec/models/xxx.rb:7:in `block (2 levels) in <top (required)>'

Finished in 0.00075 seconds (files took 0.0915 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/models/xxx.rb:6 # RSpec matcher should ensure that attributes are validated```

Clearly, I don't know what I'm doing. How can I get this test to work?

**Comment by kritik** [comment]
To be honest I don't know how to help you. Tests are passing and this gem is working in production. So, seems problem in your test

**Comment by Quintasan** [comment]
For some reason I have the same problem.

My model:
```ruby
class LawProposal < ApplicationRecord
  validates :name, presence: true
  validates :url, presence: true, url: { allow_nil: true }
end
```

My spec file:
```ruby
require 'rails_helper'

RSpec.describe LawProposal, type: :model do
  subject { LawProposal.new }

  context "validations" do
    it "has a name" do
      expect(subject).not_to be_valid
    end

    it "has an url" do
      should validate_url_of(:url)
    end
  end
end
```

Error
```
Starting polikompas_gems_1 ... done
/usr/local/bin/ruby -I/gems/gems/rspec-core-3.8.0/lib:/gems/gems/rspec-support-3.8.0/lib /gems/gems/rspec-core-3.8.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

Randomized with seed 3592

LawProposal
  validations
    has a name
    has an url (FAILED - 1)

Failures:

  1) LawProposal validations has an url
     Failure/Error: should validate_url_of(:url)

     NoMethodError:
       undefined method `validate_url_of' for #<RSpec::ExampleGroups::LawProposal::Validations:0x000055843aa8e490>
     # ./spec/models/law_proposal_spec.rb:12:in `block (3 levels) in <top (required)>'

Finished in 0.09553 seconds (files took 2.2 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/models/law_proposal_spec.rb:11 # LawProposal validations has an url
```

**Comment by MothOnMars** [comment]
Same issue here. I opened the above PR to resolve the issue.
